container.ini, scripts/python/cobbler_add_distros.py
Use xorriso instead of 7z to extract iso images. Installation files must
retain their original names but 7z limits filename character length.
Change-Id: I2ad6f3677eab86e4eb3da2d27c8a137bcac40391
=> fix: Use xorriso to extract iso images

scripts/python/lib/db.py
The 'inventory.yml' file is kept inside of the LXC container. For
convenience a soft link is created on the deployer pointing to the
'inventory.yml' with the container file system. If the container is
destroyed the link will be broken. This patch will remove the link if it
is broken allowed it to be replaced by an empty file.
Change-Id: Ic1795c68738b137ec676ea1e5016e61862b5d375
=> fix: Remove broken link to inventory file

playbooks/templates/persistent-net-rules.j2
If an interface is configured to be renamed but doesn't have a MAC
address defined in inventory then udev rule will not be created.
=> fix: Do not rename interfaces without MAC address

scripts/python/gen.py, scripts/python/lib/config.py, scripts/python/lib/validate_config_logic.py
Check node template physical interfaces for duplicate ports, valid
references to top level interface definitions and switches and valid 
rename values.
=> feat: Add checks to config file logic validation

scripts/python/lib/config.py
The top level 'config.yml' key 'networks' should be optional.
=> fix: Do not require 'networks' key in config file

scripts/python/lib/mellanox.py
Correct regular expression in mellanox.py:is_mlag_configured.
=> fix: Handle is_mlag_configured

scripts/python/cobbler_add_systems.py
The 'users' list in 'node_templates: os' should be optional.
=> fix: Do not require 'node_templates: os: users:'

scripts/python/lib/config.py
The 'interfaces' and 'network' lists defined within a 'node_templates'
item are optional. If the key is included without a value then it will
now be treated as if it were not defined.
=> fix: Ignore node template items with empty values

tests/commit_message_validate.py
Modify commit message validation rules to allow 'Merge' as a subject
tag. When a 'Merge' tag is used the subject length is not limited to 50
characters.
=> feat: Allow merge commits

tox.ini
Running the tox ansible-lint environment results in the following error:
[ANSIBLE0014] Environment variables don't work as part of command
/home/jwcarman/projects/ibm/cluster-genesis/playbooks/tasks/cmd_bootstrap.yml:18
Task/Handler: Run Bootstrap Command
The error is generated due to using jinja2 variables inside the 'args'
value, _not_ environment variables. This has been tested (lightly) but I
think it's safe to ignore this error class for now to allow tox to run
cleanly.
=> fix: Ignore ANSIBLE0014 in tox ansible-lint env

tests/commit_message_validate.py
Modify commit message validation to ignore any pull request reference at
the end of the subject line when checking that there are no more than 50
characters.
=> test: Allow pull request ref in commit subject

os-images/os-image-urls.yml
Ubuntu 16.04.4 installation images have been released. URLs provided to
automatically download installation images need to be updated.
=> feat: Update Ubuntu install image URLs for 16.04.4

scripts/python/gen.py
Make import conditional so that the config file is not parsed prior to
being validated.
=> fix: Make import conditional

scripts/python/lxc_conf.py
Create needed paths for unprivileged Linux containers if they don't
already exist. This fixes first time run failure of container
creation.
=> fix: Create lxc paths

scripts/python/lib/genesis.py
The module 'genesis.py' assumed the top-level project directory would be
named 'cluster-genesis'. Git allows a project to use any name for the
top-level directory and so should we. After renaming the project GitHub
repository this is especially problematic since the default directory
name is now 'power-up'. This commit changes the 'GEN_PATH' algorithm to
rely on the relative location of the 'genesis.py' module. If
'genesis.py' were to be moved this code would also need to be updated.
=> fix: Detect top-level project directory name

scripts/setup-env
Using the git command 'git rev-parse --show-toplevel' to determine the
path of the top level POWER-Up directory allows 'setup-env' to:
1) Use any name for the project directory
2) Source 'setup-env' from any directory within project
=> fix: Auto detect project root in 'setup-env'

scripts/cleanpath, scripts/setup-env
When 'setup-env' copies the 'cleanpath' script to '~/bin/cleanpath' sed
is used to set the 'PROJECT_ROOT' variable. This allows 'cleanpath' to
clean the shell's PATH regardless of the top level project directory
name, even after the project directory has been removed.
=>  fix: Auto set project root in 'cleanpath'

scripts/python/lib/db.py
Allow schema and logic validation of arbitrary config files without an
existing run-time config file.
=> fix: Allow validation without run-time config file

playbooks/host_vars/deployer, playbooks/host_vars/localhost
Change project name references in Ansible 'host_vars' files from
'cluster-genesis' to 'power-up'. TODO: Add logic to allow any top level
directory name.
=> fix: Update project name in Ansible 'host_vars'

.gitignore, scripts/install.sh
If 'teardown' is run before a log file ('logs/gen') is created then the
log file will be created with 'root' user as the owner and without write
privileges for other users. Subsequent attempts to write to the log file
as a non-root user will fail. Tracking a blank log file in the project
repository will ensure it will be created with the cloning user as
owner.
=> fix: Create empty log file to ensure user is owner

scripts/python/lib/validate_config_schema.py
The configuration file top-level key 'networks' is not required.
=> fix: Do not require top-level 'networks' in config

scripts/python/lib/validate_config_logic.py
A config file logic check erroneously called a 'data' interface method
when checking 'pxe' interfaces.
=> fix: Correct PXE interface logical validation

docs/Config-Specification.rst, sample-configs/basic.config.red-hat.yml, sample-configs/basic.config.ubuntu.yml, sample-configs/mlag.config.red-hat.yml, sample-configs/mlag.config.ubuntu.yml, sample-configs/non-func-comprehensive.config.yml, sample-configs/simple_flat.config.ubuntu.yml
User passwords set in the config file 'node_templates: os: users:' must
be crypted. These dictionaries are passed to the Ansible 'user' module,
which no longer supports plaintext passwords. The config spec and sample
configs have been updated to show the requirement more clearly.
=> docs: Document user password requirements

scripts/install.sh
In Ansible 2.5.0 'gather facts' requires 'dmidecode' software to be
installed on clients. This is considered a bug
(https://github.com/ansible/ansible/pull/38001). The previous Ansible
version, 2.4.3.0, is not exposed and seems to be working fine.
=> fix: Use Ansible version 2.4.3.0 instead of 2.5.0

scripts/python/lib/config.py
The 'physical_interfaces: data:' list in the config file is optional.
When it is not included the 'config.py' method to get data interfaces
should returns empty list and the method to get the list size returns
'0'.
=> fix: Do not require 'data' physical interfaces

scripts/python/lib/container.py
When running commands inside the container 'stderr' is now written to
file (along with 'stdout') instead of printing to the user's 'stdout'.
There's no need to clutter the output if return codes from the commands
are good and then script continues running.
Output from container commands are written to a '.log' file inside the
'logs/' directory.
=> fix: Improve 'pup' output when creating container

docs/Config-Specification.rst, scripts/python/cobbler_add_systems.py
The OS profile defined in config.yml 'node_templates: - os: profile:'
value can match the installation image file exactly (including the
".iso" extension), or match the name excluding the ".iso" extension.
=> refactor: Allow OS profile to end with ".iso"

os-images/config/RHEL-7-default.ks
The default kickstart no longer sets up SSH keys or passwordless sudo
for 'defaultuser'. If desired this can be accomplished through
post-deploy "software_bootstrap" scripts.
=> fix: Remove 'defaultuser' scripts from kickstart

scripts/python/gen.py
Config file validation creates an inventory file (in project root
directory) to flush out any errors before deployment starts. The
'inventory.yml' that gets created will later be replaced with a link to
the inventory inside the container file system.
=> feat: Create inventory as part of config validate

scripts/teardown
The 'teardown deployer --all' needs to be handled by the 'teardown' bash
script so the network portion can be run by root (using 'sudo') and the
container portion run by the user.
=> feat: Enable 'teardown deployer --all'

tox.ini
There is no need to create separate, identical python virtual
environments for each tox test. On my laptop tox runs twice as fast by
by re-using single environment.
=> test: Use single tox python venv for all tests

container.ini, scripts/python/cobbler_install.py
Several minor Cobbler and Apache2 configuration warnings are addressed
to "clean-up" the 'pup' output.
=> fix: Clean-up Cobbler and Apache2 configuration

scripts/python/enable_deployer_networks.py
Give user the option to terminate deployment if the pxe or ipmi
bridges already exist. This is primarily intended as a check in
multi tenant environments.
=> feat: Prompt if deployer bridges already exist

scripts/python/gen.py, scripts/python/lib/inv_nodes.py
Move test creation of inventory.yml to power-up/logs so as to not
interact with symlink creation.
=> fix: Write test inventory.yml to power-up/logs

scripts/pup
When running 'pup deploy' 'setup --all' need to be called in order to
include deployer gateway configuration.
=> fix: Call 'setup --all' from 'pup deploy'

scripts/python/cobbler_install.py
Cobbler commit e1c6aa5 backported a feature to manage '/etc/genders'.
This commit does not include a default setting for 'manage_genders' to
be used when it is not included in the config file.
This commit should be reverted when Cobbler 'release28' branch is fixed.
=> fix: Disable Cobbler 'manage_genders' by default

scripts/python/lib/validate_config_logic.py
Check that for all management networks that have a bridge
defined, the bridge and container ip are in the same subnet.
=> fix: Validate config logic

scripts/python/cobbler_install.py
This reverts commit ce030abd87197db7ff37d9c745e770aa49466d3c.
Fix was accepted in upstream Cobbler repo
(https://github.com/cobbler/cobbler/pull/1896).
=> Revert "fix: Disable Cobbler 'manage_genders' by default (#125)"

README.rst
Freenode provides an in-browser "webchat" interface that we can link
directly to from the README.
=> docs: Change README to reference IRC channel

README.rst
IRC channel has been changed to '#power-up' to match the new project
name.
=> docs: Update IRC channel

scripts/python/lib/container.py, scripts/python/remove_client_host_keys.py
POWER-Up will automatically create an SSH private/public key pair if it
does not already exist. If a '.ssh' directory does not exist in the
user's home directory it needs to be created before the SSH key pair can
be written to file.
=> fix: Create user '.ssh' directory if needed

scripts/venv_install.sh
Ansible version '2.5.2' has a bug that will display "[ERROR]:" when
running a dynamic inventory script
(https://github.com/ansible/ansible/issues/39007) due to an appended new
line character. This issue is resolved by
https://github.com/ansible/ansible/pull/39019 which is included in
Ansible version '2.5.5'.
=> fix: Update Ansible pip package to '2.5.5'

scripts/venv_install.sh
Ansible version '2.5.2' has a bug that will display "[ERROR]:" when
running a dynamic inventory script
(https://github.com/ansible/ansible/issues/39007) due to an appended new
line character. This issue is resolved by
https://github.com/ansible/ansible/pull/39019 which is included in
Ansible version '2.5.5'.
=> fix: Update Ansible pip package to '2.5.5' (#163)

software/paie52_ansible/install_anaconda.yml, software/paie52_ansible/install_cudnn.yml, software/paie52_ansible/install_nccl.yml, software/paie52_ansible/run.yml
Several of the paie52 install tasks reference an IP address to reach the
installer node. The 'ip_route_get_to.py' script is used to dynamically
insert an IP with a route to each individual client node.
=> fix: Use IP route to get installer IP address

software/paie52_ansible/install_anaconda.yml
Add Anaconda2 install location to PATH in user's '.bashrc'.
Change install directory to default '~/anaconda2'.
If '~/anaconda2' directory already exists use '-u' argument with the
installation script to update the existing files.
=> fix: Append Anaconda install dir to PATH

scripts/python/software_hosts.py, software/paie52.py
Change the order and wording of the software inventory configuration
prompts so the "good" path to continue is the first option.
If a user has already completed the software inventory setup routine in
'--init-clients' then '--install' only needs to run validation. If
validation passes installation can continue without prompting, else if
validation fails the user will be presented with the software inventory
setup routine.
=> refactor: Improve software inventory prompts

playbooks/lookup_interface_names.yml
The playbook 'lookup_interface_names.yml' is used to merge dictionaries
mapping all client node MACs to interface names.  It's possible for
environmental variables on localhost to cause jinja template errors when
they container "{{" "}}" characters. The play was run on all hosts but
only needs to be run on client nodes so this fix limits iteration over
client nodes only.
=> fix: Limit host list in 'lookup_interface_names'

software/paie52.py
Print a message if a play include tasks that may result in client node
reboots.
Print a message indicating that the SUDO prompt requires the client node
password.
=> feat: Improve 'software --install' messages

software/paie52_ansible/disable_udev_mem_auto_onlining.yml
When re-running the playbook to disable udev memory auto onlining
there's no need to reboot client nodes if nothing has changed. With a
few modifications to the task Ansible will be able to use built-in
"changed" logic to prevent multiple reboots.
=> refactor: Prevent multiple reboots from udev rules

software/paie52_ansible/install_cudnn.yml, software/paie52_ansible/install_nccl.yml
Cuda directories (cuda-dnn and cuda-nccl2) need to be updated in Ansible
install tasks due to commit a8a1916.
=> fix: Update Cuda directory links in Ansible tasks

software/paie52.py, software/paie52_ansible/anaconda_install.yml, software/paie52_ansible/anaconda_prep.yml, software/paie52_ansible/install_anaconda.yml, software/paie52_install_procedure.yml
The IBM Knowledge Center instructions specify to install Anaconda into
the '/opt/anaconda2' directory.
=> fix: Install Anaconda to '/opt/anaconda2'

software/init_clients.yml, software/paie52.py
The 'paie52.py' 'init_clients' method passes the 'software-vars.yml'
path via Ansible's '--extra-vars' argument.
Logic is added to verify the 'init_clients.yml' playbook runs
successfully, and allows for user selected retry/continue/exit on
failure.
=> fix: Use generated 'software-vars.yml' path

scripts/python/configure_mgmt_switches.py, scripts/python/switch-cfg.py
Optionally remove management switch ports from pxe and ipmi vlans if
they have not been specified in the config file.
Make configure_mgmt_switches idempotent.
=> feat: Remove unspecified ports from vlans

scripts/python/gen.py
Properly set container config file path when a directory is included
in the config file path specified on the command line.
=> fix: Set container config file path

software/paie52.py, software/paie52_ansible/anaconda_install.yml
If a '~/.condarc' file does not exist create it. Append an entry
pointing to installer 'repos/anaconda/pkgs/free/linux-ppc64le/' in
'channels' list.
=> fix: Add '.condarc' with installer channel

scripts/python/lib/genesis.py, scripts/venv_install.sh, software/paie52.py, software/paie52_ansible/sudo_test.yml
The client sudo password (must be the same for all client nodes) can
optionally be encrypted and stored in 'software-vars.yml'. Ansible Vault
is used to encrypt the password.
=> feat: Allow client sudo password to be cached

software/paie52_ansible/configure_spectrum_conductor.yml
Uninstalling the 'protobuf' pip package is not necessary before
installing DLI dependencies.
=> fix: Do not 'pip uninstall protobuf'

software/paie11.py
Any 'pup' process instantiating a 'software' object will delete the
'.vault' file upon termination. If more than one 'pup' process is run
concurrently each process needs to verify the existence of the '.vault'
file before attempting to use it. The vault password is stored as an
attribute and thus can be used to re-unlock without re-prompting the
user.
There is still a small chance that the '.vault' file is removed
in-between checking for it's existence and starting up the
'ansible-playbook' sub-process. In this case a retry will be required.
=> fix: Always unlock vault before running plays

scripts/python/software_hosts.py
Ansible should be usable outside of the pup program without root access.
Any SSH keys used int he Ansible inventory need to be accessible by the
user.
=> fix: Do not use private SSH keys from '/root' dir

scripts/install.sh
Remove vlan from the list of packages installed by POWER-Up's install
script. Vlan package is not needed (does not exist). Vlan support
(8021q) is enabled in RHEL 7+ by default.
=> chore: Remove vlan from RHEL packages

scripts/python/lib/validate_config_logic.py
Individual system hostnames and any node 'roles' are valid
'software_bootstrap:' 'hosts:' values.
=> fix: Allow hostnames and roles as bootstrap hosts

software/get-dependent-packages.sh
When using 'sshpass' to make 'ssh' calls, if host key is not present in
a user's 'known_hosts' file the script will fail without any output to
stdout or stderr (rc=6). If this situation is encountered within
'get-dependent-packages.sh', the user is left without any information on
why the script failed in a situation that is easily remedied. Logic is
now preset to check if the host key exists, if it does not then it is
added automatically (a message is printed to stdout to notify the user).
=> fix: Add host key in get dependent package script

software/paie52_ansible/configure_spectrum_conductor.yml
All tasks use a common 'become' password. Mixing 'become_method: sudo'
(default) and 'become_method: su' inherently assumes that a user's sudo
password and the root account password are the same. This is not a valid
assumption so 'become_method: su' cannot be used.
=> fix: Remove 'become_method: su' from tasks

scripts/python/software_hosts.py
This should take care of issue #4252 (I have not tested it, though).
=> fix: Verify SSH dir exists before reading keys

software/paie111.py, software/paie111_ansible/install_spectrum_conductor_dli.yml
Correctly handle task name change in playbook
install_spectrum_conductor_with_spark.yml. Task name "Install
Spectrum conductor with spark" changed to "Install Spectrum
conductor". This caused the install function in paie111.py to
not create the environment variables file.
=> fix: Handle environment variables

scripts/python/lib/utilities.py
Include the /root directory (recursively) when searching for content
files.
=> feat: Include /root in file searches

software/paie111_ansible/disable_udev_mem_auto_onlining.yml
The udev Memory Auto-Onlining Rule is only required for POWER9 servers.
=> fix: Limit memory udev rule change to POWER9 nodes

scripts/python/software_hosts.py
The PAIE installer does not yet support redundant master hosts, so the
template is updated to show a single master.
Non-master hosts are referred to as "compute" hosts (not "worker").
=> fix: Update software hosts template

docs/Running-paie.rst
Update documentation for setting up multiple users. Each user must
install their own copy of POWER-Up.
=> docs: Update installer node setup

scripts/python/inv_add_ports.py, scripts/python/lib/switch_common.py
Add a randomized sleep delay after surrendering a switch lock to give
other processes a chance to access the switch.
=> fix: Add delay after switch communication

software/paie111.py
Update cuda-dnn and nccl versions in README that paie111.py displays.
=> fix: Update README with latest software versions

scripts/python/lib/argparse_gen.py
Usage output for 'pup' is still using "Cluster Genesis" and "gen.py".
This also needs to be fixed in 'master' branch.
=> fix: Update 'argparse_gen.py' to use 'pup'

scripts/python/software_hosts.py
I mistakenly thought that pathlib 'Path.home()' would return the 'root'
user's home directory when 'software_hosts.py' was called using sudo.
This caused the logic to verify client hosts keys were in 'known_hosts'
files to only check the user file.
Now the logic specifically adds the root 'known_hosts' file
('/root/.ssh/known_hosts') to be checked in the case of sudo calling the
script.
=> fix: Check 'root' known_hosts for client host keys

scripts/python/software_hosts.py
If client host keys are not present in either '/root/.ssh/known_hosts'
or '~/.ssh/known_hosts' they will be added without a prompt (a message
will be printed to stdout).
Prompting is left in place in the event of conflicting host keys.
=> refactor: Add client host keys without prompting

scripts/python/software_hosts.py
If a client node inventory file is not found (e.g. initial run on
'--init-clients') transition right into creating an inventory without
any "file not found" messages. This makes it more clear to a user that
they are _not_ on an error path.
=> refactor: Change prompt to create new inventory

software/paie111_ansible/install_frameworks.yml
PowerAI Enterprise 1.1.1 includes PowerAI SnapML framework packages.
=> fix: Install PowerAI SnapML packages

software/pkg-lists111.yml
Add botocore back to pkg-lists111.yml and move the redundant
urllib3 entry which appears to have been pasted on top of where
botocore should be.
=> fix: Add botocore to pkg-lists111.yml

software/paie111_ansible/complete_system_setup.yml, software/paie111_ansible/powerai_tuning.yml, software/paie111_install_procedure.yml
Configuring limits for the maximum number of processors (nprocs) and the
maximum number of files open (nofile) on hosts must be done _before_
starting up services (else not all services will start successfully).
This step is described towards the end of PAIE 1.1.1 KC instructions for
"Set up your system (Manual install)"
(https://www.ibm.com/support/knowledgecenter/en/SSFHA8_1.1.1/powerai_setup.html)
and is thus moved from 'post_install_config.yml' into
'complete_system_setup.yml'.
The remaining tasks in 'post_install_config.yml' are related to PowerAI
tuning recommendations and have thus been moved into the task list
'powerai_tuning.yml'.
=> fix: Complete system setup steps before install

scripts/venv_install.sh, test-requirements.txt
Paramiko 2.4.1 is exposed to a security vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2018-1000805
Also, 'test-requirements.txt' contained pointers to old versions of
python modules (as installed by 'scripts/venv_install.sh'.
=> fix: Update paramiko due to security vulnerability

scripts/python/lib/container.py
The Cobbler web GUI fails to load because of an 'ImportError' for the
module 'ipaddress'. Cobbler uses the system level python installation so
this package needs to be installed outside of the pup python venv. The
standard Ubuntu 14.04 repos do not have a 'python-ipaddress' package
(releases >14.04 do) so the module is installed running 'pip' as root
user.
=> fix: Install 'ipaddress' python module for Cobbler

scripts/python/software_hosts.py
When checking 'known_hosts' files the '/root/.ssh' is assumed to exist.
If it does not exist it can easily be created with proper permissions.
=> fix: Create '/root/.ssh' dir if it does not exist

software/get-dependent-packages.sh
When using 'scp' to copy 'dependent-packages-paie111.list' to the remote
host there's no need to specify an absolute path to the destination.
Later in the 'get-dependent-packages.sh' when the package list is given
to 'yumdownloader' a relative path is used.
=> fix: Use relative remote path when using 'scp'

software/get-dependent-packages.sh, software/paie111.py
Read dependent packages list directly from pkg-lists111.yml. This
avoids the need for the intermediate dependent-packages-paie111.list
file and allows execution of get-dependent-packages.sh without having
previously run pup software --prep.
Use a different directory name on the remote (proxy) node. This
allows you to run get-dependent-packages.sh against the same node
it's executing on and still have the packages present when execution
completes. It also allows test execution without requiring a
separate proxy node.
=> fix: Update get-dependent-packages.sh

os-images/os-image-urls.yml, scripts/python/lib/genesis.py
Ubuntu 14.04 for ppc64el has been *removed*. The required "mini" iso
containing the installer initfs and kernel is no longer hosted by
ubuntu.com.
Ubuntu 16.04 URLs (and checksums) have been updated to point to the
16.04.5 image. It is not recommended to use older (16.04.3, 16.04.4,
etc.) install images so we should not facilitate automatically
downloading them.
=> refactor: Update Ubuntu installer image URLs

scripts/venv_install.sh
The python venv installation script, 'scripts/venv_install.sh' is
invoked in 'scripts/install.sh' with it's own shell, and thus need to
'set -e' to stop execution on errors.
=> fix: Stop on error during python venv install

os-images/config/snippets/get_ubuntu_packages, os-images/config/ubuntu-default.seed, playbooks/templates/interfaces_ubuntu.j2, scripts/python/cobbler_add_systems.py
Post-deploy network configuration for Ubuntu clients requires
'ifupdown'. Ubuntu 18.04 has 'netplan' enabled by default, but can be
disable through a kernel argument. The kernel argument to disable
netplan along with the 'ifupdown' software package will be automatically
configured if the config file 'node_templates: os: profile:' value
contains 'ubuntu-18.04'.
Also, commit 83d7f75 removed 'ntp' and 'ntpdate' packages from the
default Ubuntu preseed file. These should still be installed in Ubuntu
14.04 & 16.04, so the 'pkgsel/include' directive is now moved into a
snippet with logic to set the packages to install based on release
version.
=> fix: Disable netplan in Ubuntu 18.04 clients

os-images/config/snippets/set_ubuntu_resolv_conf, os-images/config/ubuntu-default.seed, playbooks/tasks/create_interfaces.yml, playbooks/templates/resolved.conf.j2
Ubuntu 18.04 uses systemd-resolved which requires DNS nameservers to be
set in '/etc/systemd/resolved.conf' (instead of in the '/etc/network/'
interfaces files). Also, '/run/systemd/resolve/resolv.conf' is symlinked
from '/etc/resolv.conf' for compatibility with traditional Linux
programs (see systemd-resolved manpage).
=> fix: Configure DNS nameservers in Ubuntu 18.04

software/pkg-lists112.yml
The libglvnd package and associated packages were removed from EPEL
but are now available from Nvidia.
=> refactor: Add libglvnd packages to cuda repo

scripts/install.sh
The 'pip' commands in 'install.sh' to upgrade 'pip', 'setuptools' and
'wheel' at a system level are no longer needed. All 'pip' actions should
take place inside the 'pup-venv' Python virtual environment. This was
causing a problem on a system whose 'pip' executable was located at
'/usr/local/bin/pip' but the root PATH (when using sudo) did not include
'/usr/local/bin' causing 'install.sh' to fail.
=> fix: Remove system 'pip' commands from install.sh

playbooks/activate_client_interfaces.yml, playbooks/handlers/reboot.yml, requirements.txt, scripts/python/gen.py, scripts/python/inventory.py, scripts/python/lib/inventory.py, scripts/python/set_port_macs.py
Assigning static IP addresses to client node data interfaces was not
generating MAC address table entries. Using dhclient to force a single
DHCP request (with a timeout of 1 second) works reliably.
=> fix: Use 'dhclient' to build post-deploy mac table

scripts/install.sh
IPV4 forwarding needs to be enabled to allow Docker containers to access
networks through the host (e.g. internet).
=> fix: Ensure IPV4 forwarding is enabled

playbooks/activate_client_interfaces.yml
RHEL defaults to enabling zero-configuration routes when a DHCP request
fails. Since switching to use 'dhclient' to activate data interfaces
(for MAC address harvesting - see 1827702) all data interfaces are left
with "extra" zerconf routes.
=> fix: Disable RHEL zeroconf routes

playbooks/configure_operating_systems.yml, playbooks/tasks/create_interfaces.yml
Since the PXE interface is using during OS installation a 'ifcfg-*'
script is automatically generated. If this interface is renamed and
reconfigured during post-deploy the original 'ifcfg-*' script is left in
place and causes systemd to report errors when starting
'network.service'. Instead of removing the 'ifcfg-*' script this patch
sets 'ONBOOT=no' so that 'network.service' does not try to activate it.
I have not tested Ubuntu to see if similar behavior exists there. This
patch only affects RHEL client nodes.
=> fix: Disable stale PXE ifcfg-* script if renaming

docs/Config-Specification.rst, os-images/config/RHEL-7-default.ks, os-images/config/ubuntu-default.seed, scripts/python/cobbler_add_systems.py, scripts/python/lib/inventory.py
Set static hostname and domain using 'hostnamectl' (called at install
time through the kickstart/preseed file).
Add optional 'domain' key in config file 'node_templates: os:'
dictionary to configure domain. If a value is not specified
'localdomain' will be used.
=> feat: Set static hostname and domain

playbooks/ansible.cfg, scripts/python/software_hosts.py
The Ansible 'minimal' callback plugin formats json output with line
breaks and indentation. This eliminates the need for the
'ansible_pprint' function in 'scripts/python/lib/utilities.py' - calls
to this function should be removed in the next 'paie*' module release.
Retry files are not used and create clutter.
=> refactor: Update Ansible config for cleaner output

scripts/python/inventory.py
The post-deploy task to transfer SSH key pairs and the inventory file to
any client nodes assigned the 'solution_keys' and 'solution_inventory'
roles generates a prominent warning messages when the role is not
present. The dynamic inventory script would only create Ansible groups
for defined roles. This commit create empty 'solution_keys' and
'solution_inventory' Ansible groups in order to suppress the "[WARNING]:
Could not match supplied host pattern" message.
=> fix: Address post-deploy Ansible host warnings

requirements.txt
The 'paramiko' python module depends on the 'cryptography' module. There
is a known 'CryptographyDeprecationWarning' problem (see
https://github.com/paramiko/paramiko/issues/1369) that can be resolved
by installing 'cryptography==2.4.2'.
=> fix: Resolve 'CryptographyDeprecationWarning'

software/paie111_ansible/reboot.yml, software/paie112_ansible/reboot.yml, tox.ini
Rule "[204] Lines should be no longer than 120 chars" is added to the
exception list. There isn't a good way to split encrypted password
values in config files across multiple lines.
=> test: Address tox ansible-lint environment fails

scripts/install.sh, scripts/python/lib/utilities.py, scripts/python/osinstall.py, tests/commit_message_validate.py, tests/unit/test_pup_osinstall.py
These patches add:
* keyboard exception handling in osinstall.py
* Check for existing dhcp servers given an interface using nmap
=> Check for existing DHCP servers#6351 

playbooks/tasks/redhat_subscription.yml
Commit 2357dc7 failed to name one of the added tasks and causes the
'ansible-lint' tox test to fail.
=> chore: Name Ansible task to pass 'ansible-lint'

scripts/install.sh
When installing multiple packages at the same time yum will still exit
cleanly if some of the packages are missing. There is an option to force
an exit with error if _any_ package is missing. All packages installed
via the 'scripts/install.sh' script are required and thus the software
should halt if it is unable to install something.
=> fix: Exit yum with error if package is missing

playbooks/lookup_interface_names.yml, playbooks/tasks/create_interfaces.yml
Commit 28743e1 (PR #323) disabled "ONBOOT" loading of _any_ ifcfg script
with a device name that didn't match a physical device name in
inventory. This commit changes the logic to _only_ disable "ONBOOT" in
ifcfg names match the original device name of a *changed* interface. All
other interface configuration scripts are left alone.
=> fix: Only disable stale 'ifcfg' scripts

scripts/python/configure_mgmt_switches.py, scripts/python/repos.py, scripts/python/show_mgmt_switches.py, scripts/python/show_status.py, software/get-dependent-packages.sh
This cleans up the remaining tox errors in master branch:
- software/get-dependent-packages.sh:50:1: E006 Line too long
- scripts/python/show_status.py:156:25: F823 local variable 'input'
defined as a builtin referenced before assignment
- scripts/python/repos.py:157:9: E117 over-indented
- scripts/python/configure_mgmt_switches.py:85:17: E117 over-indented
- scripts/python/show_mgmt_switches.py:155:25: F823 local variable
'input' defined as a builtin referenced before assignment
=> refactor: Fix tox errors

scripts/setup-env
By editing a single line in the python venv 'activate' script we can
include the pup script directories and make use of the prompt update and
'deactivate' script.
=> feat: Show 'pup-venv' in prompt

playbooks/activate_client_interfaces.yml
- Increase dhclient timeout and post-activation wait time to allow
additional time for switch mac-address-table to be updated.
- Release any existing dhclient leases ('dhclient -r') before activate
each interface. This is necessary if any interface successfully
obtains a DHCP lease (previously would cause the _next_ interface to
fail due to existing 'dhclient' process still running).
=> fix: Tune data interface MAC address collection

scripts/python/lib/lenovo.py
When reading port information from a lenovo switch the output is split
to allow viewing one page at a time (similar to unix 'more'). Port 26 is
listed after the "continue" text which caused the parser to drop the
data.
=> fix: Remove "continue" line from lenovo switch out

scripts/python/osinstall.py
The 'Scan for nodes/Stop node scan' button is now a toggle which starts or stops
node scanning. Once scan mode is set, a new scan is initiated (n) seconds
after the last scan finished and repeats until the toggle is pressed.
=> feat: Scan target nodes on periodic loop

sample-configs/simple_flat.config.ubuntu.yml
The 'ansible-lint' tox environment fails due to a duplicate key found in
'sample-configs/simple_flat.config.ubuntu.yml'.
=> fix: Remove duplicate key from sample config

scripts/python/gen.py
The contents of the 'os-images' directory are archived and copied into
the container. The archive can become quite large if multiple OS images
are present. The files and directories can be copied one at a time to
reduce the total memory required to load the archive.
=> fix: Copy 'os-images' content one item at a time

scripts/python/lib/inventory.py
Set switches to empty list in inventory to prevent error msg.
This is a place older for switches in inventory.
=> fix: Set siwtches in inventory

scripts/python/lib/container.py
Replace complicated image list filtering with a simple
'client.images.get()' call.
=> fix: Use 'client.images.get()' to check for images

scripts/python/lib/container.py, scripts/python/lib/db.py
The 'DatabaseConfig' class will accept a relative config file path
without controlling the current working directory. If the python working
directory is changed then a previously valid relative config path can
become invalid (see next paragraph). If a path is invalid it's worth
joining it with the project root directory and checking again.
The 'Container' class 'copy' method changes the working directory
without cleaning up after itself.
=> fix: Convert relative config path to absolute

scripts/python/lib/lenovo.py, scripts/python/lib/switch_common.py
Lenovo switches add extraneous characters for line paging. A class
method is added to allow unique sanitation logic for each vendor switch
class.
=> fix: Add switch class 'sanitize_line' method

scripts/python/inv_create.py
The same inventory file is used to store 'InventoryNodes' and
'InventorySwitches' class data. Existing content is loaded from file
(_not_ from any existing objects). The 'update_' method can be called to
write data to file without relying on object deletion and allowing for
subsequent 'InventoryNodes' or 'InventorySwitches' objects to loaded
current content.
=> fix: Call inventory update methods directly

software/pkg-lists-wmla120.yml
Changed package to an older package in pip list also added from list in conda main package. Seems there is another bug in parsing of correct data from the parser package tool.
=> fix issue 7619 of missing package

scripts/python/software_hosts.py
When software_hosts attempts to Ansible ping client nodes and is
unsuccesul, the displayed msg was being misinterpreted as a possible
error. A new message with greater detail is now displayed.
=> fix: Additional detail in msg post Ansible ping

sample-configs/profile-template.yml
Remove the PXE address mode selection field from the osinstall
network form. If needed this can be handled in a post deploy stage.
=> fix: Remove pxe addr mode selection

scripts/python/gen.py
If invoking osinstall from pup, use sample-configs/
profile-template as the profile when no profile.yml exists.
=> feat: Use profile template if none specified

requirements.txt, test-requirements.txt
PyYAML 5.1 is failing to load tag !vault. Reverting to 3.11 in requirements.
=> fix: Issue 8216, PyYAML 5.1 is failing

software/wmla120.py
Skip creation of pypi repo when user responds no.
=> fix: Handle 'no' response in pypi repo setup

scripts/python/lib/utilities.py, software/wmla120.py
When setting up the dependencies repository the user selects to sync
either P8 or P9 packages. If and _only if_ the installer is running the
same model processor the packages can be synced from locally enabled yum
repositories. This commit removes the option to sync from enabled repositories
when the installer and client nodes do not have the same model of POWER 
processors.
=> fix: Prevent P9 package sync from P8 installer

scripts/python/repos.py
Undo previous change which specified a python version and instead
mask the weave build error as is done with functools32 package.
Previous change was failing if pip is not installed for python2.7.
=> fix: Hide pypi error on weave download

software/pkg-lists-wmla120.yml, software/pkg-lists-wmla120_x86_64.yml
Add wget and ntp to package lists. These were not resolved by package
dependency tooling as they are included in the pup kickstart file.
=> fix: Add packages to pkg-lists

scripts/install.sh
The 'bzip2' utility is required to extract 'bz2' archives.
=> fix: Install 'bzip2' package on RHEL installer

scripts/python/cobbler_add_distros.py, scripts/python/lib/utilities.py
The 'extract_iso_image' utility function needs to return relative kernel
and initrd paths. The caller can then join the relative paths to a local
directory path (for Cobbler setup) or an http URL (to directly setup a
pxelinux configuration).
=> fix: Return relative paths in 'extract_iso_image'

scripts/install.sh
Skip installation of syslinux-tftpboot on POWER9 systems since it
is not available at this time. This allows PowerUp to be installed
on POWER9 systems albiet without osinstall capability.
=> fix: Skip installation of syslinux-tftpboot

scripts/python/lib/utilities.py
Refracting a typo to use re.search module
=> Fix: parse_rpm_filenames using single package details failure

os-images/config/RHEL-7-default.ks.j2, os-images/config/pup_report.sh, os-images/config/ubuntu-default.seed.j2, scripts/python/lib/utilities.py, scripts/python/osinstall.py
Client nodes are selected for OS installation based on system
information collected from the BMC through IPMI commands. There is not a
good way to programmatically query installation status through IPMI
commands. Instead, the installer http service can be configured to allow
client installers to report status via 'PUT' calls. Scripts called
through the kickstart/preseed files collect various system information
and send it to the installer in json format.
Requiring the user to provide a device path for the OS installation disk
is prone to error. For the case that it does not matter which disk is
selected (single disk installed, test system, etc.) kickstart/preseed
scripts allow automatic selection of "first" (non-deterministic) disk
device for OS installation.
=> feat: Enhance 'osinstall' installer automation

playbooks/activate_client_interfaces.yml
Add '-n' dhclient option to client nodes running Ubuntu to speed up data
MAC address collection. This option prevents the interface from
accepting a DHCP lease (for some reason it causes 'dhclient' to hang in
RHEL).
=> refactor: Improve Ubuntu data MAC collection

software/wmla120.py
Install Nginx before trying to verify that content under the software
root directory can be accessed by nginx.
=> fix: Install Nginx before verifying access

software/wmla120.py
Show 'complete' in display of software install status when the firwall
is disabled or enabled and configured for http.
=> fix: Allow status complete with firewall disabled

software/wmla120_ansible/uninstall_wmla120.yml
Wmla uninstall can leave dangling packages if uninstall is unable to remove them. This fix addresses correct removal of those packages through a shell script in ansible.
=> fix: Uninstall issue related to dangling packages.

software/wmla120_ansible/uninstall_wmla120.yml
There is an issue when user uses egoadmin as user to uninstall the wmla software. This script removes the check as egoadmin as it will remove the ssh connection and logout the ansible script which will cause the script to fail. Minor added resilience to stopping all computing services.
=> fix: Uninstall issue related to egoadmin

software/wmla120_ansible/env_vars/setup_private_env_vars.yml
Using rhel76 user in mount point template will lead to failures
when the template is used unedited. If we use existing user
like nfsnobody such issues can be avoided.
=> fix: Change mount point template to avoid using rhel76 user

scripts/python/pupteardown_deployer_networks.py
Add try and except on container network teardown to allow teardown of
deployer networks to continue if the container is 'missing'.
=> fix: Handle missing container

scripts/python/validate_cluster_hardware.py
Regular expression 're.search' will return 'None' if no match is found.
Attempting to user 'start()' method on 'None' causes an
'AttributeError'. Inspecting the request info only needs to be done if
're.search' find a match.
=> fix: Verify regex match is not 'None'

scripts/python/validate_cluster_hardware.py
Commit 68db71d replaced the 'ValidateClusterHardware' '_power_all'
method with 'set_power_clients' and 'set_bootdev_clients'.
=> fix: Remove calls to '_power_all' method

requirements.txt, scripts/python/format_yaml.py, scripts/python/lib/db.py, scripts/python/lib/genesis.py, scripts/python/lib/ipmi.py, scripts/python/osinstall.py, scripts/python/str2dict.py, scripts/python/switch_cfg.py, software/get-dependent-packages.sh, software/paie111.py, software/paie112.py, software/wmla120.py
Python module 'PyYaml' version '4.2b1' and earlier used a default loader
that allowed arbitrary code execution. Updating the 'PyYaml'  module to
version '5.1' and always specifying the Loader (using shortcut "sugar"
method 'yaml.full_load') allows for "safe" loading without deprecation
warnings.
=> fix: Specify PyYaml Loader

requirements.txt
Ansible '2.7.1' fetch module is exposed to a security vulnerability that
is fixed in >= '2.7.8'. (https://nvd.nist.gov/vuln/detail/CVE-2019-3828)
=> fix: Update Ansible module

scripts/python/format_yaml.py, scripts/python/lib/db.py, scripts/python/osinstall.py, software/wmla120.py
The 'yaml.full_load()' function is a shortcut to call
'yaml.load(input, Loader=yaml.FullLoader)'. When specifying a Loader (in
this case 'Loader=AttrDictYAMLLoader') the 'yaml.load()' function should
be called.
=> fix: Do not call 'yaml.full_load()' with 'Loader='

tox.ini
when running ansible-lint with *_install_procedure*.yml, causing it to fail due new validation procedure, this now covers all procedures.
=> fix: address ansible-lint fail by removing all procedure files

scripts/python/create_base_dir_wmla120.py, scripts/python/gen.py, software/wmla120.py
Set root_dir selinux file type on move of root directory to new
root_dir directory structure.
Clear some minor tox issues.
=> fix: Set root_dir selinux file type on move

playbooks/validate_bootstrap_vars.yml
When any pup module is called that utilizes validate_bootstrap_vars.yml ,
the system hangs and fails to progress i.e.  pup validate --config-file.
When fact gathering is set to false, the deployer is able to
proceed with WMLA setup.
=> fix: Add gather facts set to false to validate_bootstrap_vars.yml

scripts/python/getdeps2.py, software/wmla120.py
Avoid subsequent failure by printing message and exiting install if data
from init clients is missing.
=> fix: Exit install if init clients has not been run

scripts/python/lib/utilities.py, scripts/python/repos.py, software/wmla120.py
Enhance get_yesno to allow a default empty response which is translated
to a yes or no based on the default yesno arg.
Enhance wmla120.py to use a default empty no prompt 'y/[n]' if a
given content or repo is already set up, and to use a default empty
yes prompt '[y]/n' if the content or repo is not setup.
=> refactor: Enhance yes/no prompts

software/wmla120.py
Remove x86 reference in readme of wmla120.py
=> fix: Remove x86 reference in readme

software/wmla120.py
Software vars '*_repo_path' keys need to be initialized using the
'_update_software_vars' method.
=> fix: Update software vars at beginning of '--prep'

scripts/python/validate_cluster_hardware.py
When validating BMC IPMI/OpenBMC credentials a count is stored to keep
track of the successful connections. When a new successful connection is
validated the count is decremented by the _total_ number of BMCs instead
of 1. This resulted in a binary pass/fail if _any_ or _no_ BMC
connections were validated.
=> fix: Decrement BMC credential count

scripts/python/osinstall.py
The 'set_*_client' modules to issue commands to BMCs include hardening
controls that can benefit osinstall.
=> refactor: Use BMC control modules in osinstall

scripts/python/lib/ipmi.py, scripts/python/osinstall.py, scripts/python/set_bootdev_clients.py, scripts/python/set_power_clients.py
Replace print with log.info in set_bootdev_clients and
set_power_clients to avoid printing to screen during OSinstall.
Remove osinstall_node_status.yml during create form.
=> fix: Return 'disk' from ipmi.hostBootSource

software/wmla120_ansible/engr_mode_client_pre_install_gather.yml
When running engr-mode function, a path to localhost is needed from ansible_env.HOME.
with out proper gathring of facts, the variable is undefined. To address this issue,
the addition of fact gathering in pre_install_gather is needed.
=> fix: Update of engr-mode to utilize ansible_env paths

sample-configs/profile-template.yml, scripts/python/osinstall.py
Pup 'osinstall' supports a single OS image per install, so the 'OS Info'
for each client will be common. To reduce width of the client status
table a global 'OS Image' field will show the basename of the
installation image selected by the user.
=> refactor: Show 'OS Info' as global status field

software/wmla120_ansible/anaconda_install.yml, software/wmla120_ansible/anaconda_prep.yml, software/wmla120_ansible/anaconda_prep_x86_64.yml, software/wmla120_ansible/engr_mode_client_post_install_gather.yml, software/wmla120_ansible/engr_mode_client_pre_install_gather.yml, software/wmla120_ansible/engr_mode_env_post_install_gather.yml, software/wmla120_ansible/engr_mode_env_pre_install_gather.yml, software/wmla120_ansible/entitle_spectrum_conductor_dli.yml, software/wmla120_ansible/entitle_spectrum_conductor_with_spark.yml, software/wmla120_ansible/install_spectrum_conductor_dli.yml, software/wmla120_ansible/install_spectrum_conductor_with_spark.yml, software/wmla120_ansible/powerai_license_install.yml, software/wmla120_ansible/wmla_license_install.yml
The Ansible variable 'ansible_user_id' is dependent on Ansible facts
collection. For any task not utilization 'become' 'ansible_ssh_user' can
be used without needing to gather facts.
=> refactor: Use 'ansible_ssh_user' var for clients

scripts/python/repos.py
Check for directory present when verifying conda repo contents.
=> fix: Conda verify packages

scripts/python/repos.py
When starting up python sub-processes the built-in 'sys.executable' can
be used as a path to the top-level python executable path. This ensures
all python processes are running with the same interpreter.
=> refactor: Use single python interpreter

software/wmla120.py
Use 'redis-*' in place of 'cython-*' as a sanity check for the right
repo when syncing content for conda-free.
=> fix: Sanity check for conda free repo

scripts/python/osinstall.py
For 'osinstall' network, when the BMC and PXE networks are using the
same interface overlapping networks are acceptable.
=> fix: Allow overlapping networks if using same ifc

scripts/python/lib/utilities.py, scripts/python/osinstall.py
DNS functionality in dnsmasq is not needed when running 'osinstall' and
causes slow network operations when turned on but configured
incorrectly.
=> fix: Disable dnsmasq DNS during osinstall

software/wmla120.py, software/wmla120_ansible/wmla_license_check_and_install_to_root.yml, software/wmla120_ansible/wmla_license_install.yml
If the WMLA license acceptance has already been completed on a node
using the user account (e.g. installer node during self-installation)
the 'status.dat' may be in the user's home directory, and the
'wmla_license_install.yml' tasks will _not_ generate a new 'status.dat'
in the root home directory.
With this fix, there is still an assumption that the license has been
accepted either as root or the WMLAE user account (typically
'egoadmin').
=> fix: Install WMLA license to root home dir 

scripts/python/repos.py
When downloading python packages from a pypi repository it is only
necessary to get the '*.tar.gz' archive. If there is a build error
(could be due to missing system dependencies on the installer, incorrect
python environment, etc.) it is safe to ignore since this it is not in
an equivalent runtime environment.
=> fix: Update pypi repo build error mask

scripts/python/create_base_dir_wmla.py, software/wmla120.py, software/wmla121.py
If files are copied from a local directory their SELinux context may
need to be changed before they will be available over HTTP.
=> fix: Always set SELinux context during '--prep'

software/wmla121.py
When running pup from one of the client nodes ("self install") reboots
will be disabled on that node. A user could also manually disable
reboots on any node through the inventory 'pup_reboot' variable. If a
client required a kernel update it should be restarted before attempting
to install CUDA drivers. This commit checks 'needs-restarting' on every
client node (regardless of the 'pup_reboot' value) and prompts the user
to perform manual reboot if any client reports it necessary. The user
may select to continue with the install without performing any reboots
(the reboot _could_ be required for non-kernel/cuda related updates).
=> fix: Check if any client needs restarting

software/pkg-lists-wmla121.yml
Some packages were listed in 'epel-ppc64le' that were already in 'epel'.
=> fix: Remove unnecessary EPEL packages

software/wmla121.py
The call to '_check_clients_needs_restarting' is missing a required
argument to pass in the client inventory.
=> fix: Add inventory argument to reboot check method

software/wmla120_ansible/configure_firewall.yml
To utilize DlI and Spectrum Conductor with the firewall enabled,
various ports are required to be set to an enable state.
Check ports status
activates ports
=> feat: Configure firewall for out-of-box install

software/wmla121.py
The Nginx status state was not being set when Nginx was not running.
=> fix: Set Nginx status when not running

playbooks/ansible.cfg
The Ansible 'get_url' module has been failing due to timeouts when
running with the installer as a cluster node. Subsequent retries are
working so possibly a larger timeout will allow it to pass on the first
try.
=> fix: Increase Ansible default timeout value

scripts/python/lib/utilities.py
If fileglobs are not found on a select remote repository the user should
be informed which ones are missing.
=> fix: Print missing files during repo check

software/content-wmla121.yml
Changing search pattern to locate ibm-wmla-license-eval_*.tar.gz
=> fix: Change search pattern for wmla eval license

software/wmla121.py, software/wmla121_ansible/install_spectrum_conductor_with_spark.yml
When running a software 'self-install' skip copying the conductor
install binary to a new folder (via http get in order to re-use logic
for remote nodes). Extra logic is added to be able to use the existing
binary in the http directory.
=> fix: Use '/srv/pup' conductor binary for localhost

software/wmla121.py
Avoid checksum validation for empty path and
prompt for user input only if checksum match fails
=> fix: Avoid checksum validation for empty path

requirements.txt
Ansible 2.7.10 is exposed to a security vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2019-10156
=> fix: Update Ansible python module version

docs/Running-paie.rst
The WMLA license is no longer a conda package so the .bin extraction
does not need to be done in a conda environment.
=> docs: Remove conda setup from .bin extraction
