playbooks/ssh_keyscan.yml
Change-Id: If9d059d09b0f7cbefc3ed5074206cff7f4c39440
=> refactor: Collect SSH host keys using config 2.0

scripts/gen, scripts/gen-ac, scripts/python/lib/argparse_gen.py
Add 'post-deploy' to auto completion and argparse_gen.py
Add --ssh-keyscan and --config-client-os to gen post-deploy sequence.
Improve consistency of gen auto completion double tab response.
=> feat: Add 'post-deploy' to gen cli

scripts/python/configure_data_switches.py, scripts/python/lib/config.py, scripts/python/lib/mellanox.py
Allows multiple bonds on nodes.
=> fix: Handle vlans and multiple bonds

scripts/python/configure_data_switches.py, scripts/python/lib/mellanox.py, scripts/python/switch-test.py
Enhance handling of MLAG to enable cluster multi-tenant.
=> feat: Enhance handling of MLAG

scripts/python/cobbler_install.py
Cobbler version 2.8.x has been released for over a year.
=> chore: Install Cobbler version 2.8

scripts/gen, scripts/gen-ac, scripts/python/configure_data_switches.py, scripts/python/configure_mgmt_switches.py, scripts/python/enable_deployer_networks.py, scripts/python/gen.py, scripts/python/inv_add_ports.py, scripts/python/lib/argparse_gen.py, scripts/python/lib/container.py, scripts/python/lib/exception.py, scripts/python/lib/genesis.py, scripts/python/lib/logger.py, scripts/python/lib/mellanox.py, scripts/python/lib/switch_common.py, scripts/python/lib/validate_config_schema.py, scripts/python/lxc_conf.py, scripts/python/validate_cluster_hardware.py
Implement initial phase of enhancements to displayed output.
=> feat: Enhance and standardize displayed output

playbooks/tasks/create_interfaces.yml, playbooks/templates/interfaces_rhel.j2, scripts/python/lib/config.py
Refactor the RHEL client network interface template for config 2.0. The
Ubuntu template was already refactored in commit 5581cf6.
=> refactor: Configure client interfaces (config 2.0)

docs/Config-Specification.rst, sample-configs/basic.config.red-hat.yml, sample-configs/basic.config.ubuntu.yml, sample-configs/mlag.config.red-hat.yml, sample-configs/mlag.config.ubuntu.yml, sample-configs/non-func-comprehensive.config.yml, scripts/python/configure_data_switches.py, scripts/python/lib/validate_config_schema.py
Add support for Red Hat style network nomenclature when configuring data
switches.
=> feat: Support Red Hat data switch configuration

scripts/python/install_client_os.py, scripts/python/ipmi_set_bootdev.py, scripts/python/lib/genesis.py, scripts/python/lib/inventory.py
Poll cobbler status for nodes installing before setting boot device
back to default. Nodes which do not initiate installation are left
unchanged.
=> refactor: Modify setboot default during install

scripts/python/validate_cluster_hardware.py
Look for clients to issue PXE boot request during cluster validation.
=> refactor: Enhance cluster validation

docs/index.rst
=> docs: Update Sphinx index

scripts/python/cobbler_install.py, scripts/python/enable_deployer_networks.py, scripts/python/lib/config.py
Move iptables NAT rule checking/creating logic into the config 2.0
python scripts.
=> refactor: Enable config 2 'deployer as a gateway'

docs/Intro-Setup.rst
Update Introduction section of Intro-setup.rst
=> docs: Update Introduction

README.rst
Update README to reflect new project name "POWER-Up".
Limit README lines to 72 characters.
Replace IRC channel reference with Gitter channel.
=> docs: Update project name in README

scripts/python/gen.py
Several messages printed by 'pup' are updated to use the new project
name.
=> chore: Update project name in 'pup' messages

scripts/python/teardown.py
Add prompt with container name before starting teardown allowing user
the opportunity to terminate.
=> feat: Prompt user during teardown

scripts/python/install_client_os.py
Add check for 'installing' when checking cobbler status.
=> fix: Handle reinstall in install_client_os.py

scripts/python/validate_cluster_hardware.py
Prevents ipmi failures due to different addresses during some
redeploy scenarios.
=> fix: Reset BMCs after validate cluster hardware

scripts/python/gen.py, scripts/python/lib/validate_config_logic.py, scripts/python/validate_cluster_hardware.py
Remove option to skip validate cluster hardware during pup deploy
when a container already exists.
=> refactor: Force validate cluster hardware

scripts/python/lib/utilities.py, scripts/python/poweraie.py, scripts/python/repos.py
Utility function get_yesno now returns True or False and accepts
a prompt value.
=> feat: Repo from rpm file

scripts/python/software_hosts.py
When a software inventory file is not found a prompt is added to confirm
that a user wants to create a new file. If the user selects "yes" at the
prompt an editor will be opened with the software inventory template.
=> refactor: Prompt user to create new inventory file

scripts/python/gen.py, scripts/python/repos.py, software/paie52.py
Change check for software class. Change base directory for
repositories.
=> refactor: Move poweraie.py to software/paie52.py

scripts/venv_install.sh
Commit 43eb2d9 backed up to Ansible 2.4.3.0 due to a 'gather facts' bug.
The bug has been fixed in Ansible 2.5.2.
=> refactor: Use Ansible 2.5.2

scripts/python/gen.py, scripts/python/lib/inventory.py, scripts/python/remove_client_host_keys.py
Before installing an OS any existing associated SSH host keys.
=> feat: Remove stale SSH host keys

playbooks/install_software.yml, scripts/python/repos.py
Repositories defined within the 'software/software-vars.yml'
'yum_powerup_repo_files' dictionary are configured on all nodes.
=> feat: Configure yum repositories on client nodes

scripts/install.sh, scripts/python/lib/utilities.py, scripts/python/repos.py, software/paie52.py
Add ability to create a repository from existing user selectable
repository. Add ability to create a repository from a repository
on disk. (enables USB support)
=> feat: Enhance repository support

scripts/install.sh
=> fix: Add createrepo to scripts/install.sh

scripts/python/repos.py, software/paie52.py
Flush repository metadata when reposync source changes.
Reorder execution flow in paie52.py so that web server is setup first,
then execute shorter tasks first with longest repositories sync'ed
last.
=> fix: Flush metadata

scripts/python/gen.py, scripts/python/lib/argparse_gen.py, software/paie52.py
Rename about to README.
Rename status-prep to status.
=> refactor: Rename about and status-prep

software/paie52.py
Add CUDA nccl v2, a late addition to PowerAI Enterprise.
=> feat: Add CUDA nccl2 to POWER-Up software server

playbooks/install_software.yml, scripts/python/gen.py, scripts/python/lib/argparse_gen.py, software/init_clients.yml, software/paie52.py
Break software install into init and install.
=> refactor: Software install

software/paie52.py
Add missing key to 'state' dictionary for NCCL v2.
=> fix: CUDA NCCL v2

software/paie52.py
Show latest files.
Add --init-clients to readme.
=> chore: Update --README

scripts/python/repos.py
Add fix to repos.py so yum caches are erased when the sync source for
a repository changes.
=> fix: Clear yum caches

scripts/pup-ac, scripts/python/gen.py
Add remaining software commands
Add auto complete for files
=> feat: Auto completion

docs/Appendix-J.rst
Add instructions to enable 'common' red hat channel.
Add hint on use of command line tab autocompletiton.
=> docs: Updates to Appendix-J

docs/Appendix-J.rst
Add notes to Appendix-J informing user that prep, init-clients and
install may be reun.
=> docs: Software installer

docs/Appendix-J.rst
Change flow slightly in Appendix-J.
=> docs: Software install

scripts/python/lib/switch_common.py, scripts/venv_install.sh
Implement locks for switches to allow multiple instances of POWER-Up
to deploy concurrently.
=> feat: Implement locks for switches

scripts/pup-ac
Allow and autocomplete directories when specifying the config file.
=> feat: Enhance auto completion

scripts/python/lib/validate_config_logic.py
Insure that all config file labels do not contain dashes ('-').
Insure that software bootstrap 'hosts' keys refer to defined node
template labels.
=> feat: Validate config file labels

scripts/python/repos.py, software/paie52.py
Create subset of Anaconda 'main' repository.
=> feat: Add Anaconda main repo dependencies

docs/Running-paie.rst
=> docs: Update software install instructions

scripts/python/software_hosts.py
User's are prompted to:
- Add host keys if none are present in 'known_hosts'
- Replace stale host keys in 'known_hosts' with current keys
=> fix: Manage SSH host keys

scripts/install.sh
Install python2-pip and upgrade to vs 18.0 to insure support for
--platform argument.
=> fix: Insure pip is installed for python2.7

software/paie11.py
Issue #3872
Handle case where user selects 'N' (None) when selecting content
to add to the software server.
=> fix: Handle 'no' (N) selection

scripts/python/repos.py, software/paie11.py
Add entitlement files for Spectrum conductor and DLI to the software
server in the same directory as the assiciated content.
=> fix: Add entitlement files to software server

docs/Running-paie.rst
Update link back to to Knowledge Center and associated verbage.
=> docs: Update link back to Knowledge Center

scripts/python/lib/utilities.py, scripts/python/repos.py, software/paie11.py
Allow user to make no url choice after having chosen to update a repo.
=> fix: Allow 'skip' of repo source selection

scripts/python/repos.py
Adjust anaconda repo sync to handle new 'alt' in repo index.html
=> fix: Anaconda main repo

scripts/python/repos.py, software/paie111.py
Check that software.vars actually contains the client repo config
information. Fix handling of 'sss' response in get_repo_url.
=> fix: Improve repo setup checks

scripts/python/software_hosts.py
When no errors occur only high level status is printed to stdout. If an
ssh key fails to copy to a client node information is printed and a more
thorough retry path is available.
=> refactor: Streamline copying SSH key to clients

software/pkg-lists111.yml
Add additional dependent packages which are not in every 'minimal'
Red hat OS install.
=> fix: Add dependent packages

docs/Running-paie.rst
Add link to Knowledge Center setup procedures.
Change 'hostname' to FQDN.
=> docs: Add link to Knowledge Center

scripts/python/get_dependencies.py, software/paie111.py, software/pkg-lists111.yml
Add all first level dependencies to dependent package list.
Add get_dependencies.py to generate dependency lists.
=> fix: Update dependent packages

software/paie111_ansible/configure_spectrum_conductor.yml, software/pkg-lists111.yml
Update software/paie111_ansible/configure_spectrum_conductor.yml
to incorporate release level changes from Knowledge Center
documentation.
=> fix: Update Spectrum DLI configuration

software/paie111.py
Spectrum conductor with Spark and DLI use environmental variables to set
configuration parameters. Users need to be able to modify these
variables each time '--install' is called.
=> fix: Always prompt to edit conductor configuration

software/file-lists111.yml, software/paie111.py, software/paie111_ansible/powerai_license_install.yml
Update software-vars content pointers at class initialization. This
insures the content pointers are set if the PowerUp software is
reloaded with the software server content still in place.
Check that software_vars contains pointers for content files when
checking software server status.
=> fix: Update software-vars content

docs/Running-paie.rst
Add a release table and instructions for how to download the appropriate
tag or latest branch release.
=> docs: Add release level information

scripts/python/repos.py, software/pkg-lists111.yml
Mask setup.py version error when executing pip download of functools32.
when executing 'python3 -m pip download --python-version 27',
functools32 generates an invalid error when running setup.py.
=> fix: Mask setup.py version error

docs/Running-paie.rst
Update software installer latest version to software-install-b2.10
=> docs: Update software installer version

docs/Appendix-A.rst
-deploys operating systems to you cluster node
updated to:
-deploys operating systems to *your* cluster node
=> docs: changes to Appendix-A

scripts/python/lib/container.py, scripts/python/lib/genesis.py, scripts/python/lib/switch_common.py
Mount /var/lock to Power-up container at /opt/.
=> fix: Concurrent deploy and switch use

scripts/pup, scripts/python/gen.py
modified:   scripts/pup
modified:   scripts/python/gen.py
=> fix: Invoke config switch as root

scripts/python/lib/container.py
=> fix: Config switch lock mount with SELinux label

scripts/python/validate_cluster_hardware.py
Updates to validate_cluster_hardware.py. Skip 60 pause for BMC reset
unless at least 1 BMC found with existing ip address.
Fix error when retry validation selected after no nodes found looking
for PXE requests.
Do not display message when 'pgrep dnsmasq' finds no existing dnsmasq.
=> fix: Update validate cluster hardware

scripts/python/gen.py, scripts/python/lib/argparse_gen.py, scripts/python/lib/genesis.py, scripts/python/lib/utilities.py, software/paie111.py
Fixed tox issues while using flake8
=> fix: Fix tox issues in flake8 testenv

scripts/python/osinstall.py
Move logger.create to main to prevent stop double logging
=> fix: Move logger.create in osinstall.py

scripts/python/gen.py, scripts/python/inv_create.py, scripts/python/lib/genesis.py, scripts/python/lib/inv_items.py, scripts/python/lib/inventory.py, scripts/python/lib/utilities.py
Add config file name to inventorynn.yml'
During deploy (create inventory), copy config file to logs/config-files/
with timestamp.
Add initial infrastructure for adding switch info to inventory file.
=> feat: Record config file

scripts/python/osinstall.py
Add additional checks and set default values if the combo netmask/
prefix field is improperly formed. User can now also enter a netmask
without a prefix or a prefix without a netmask.
=> fix: Handle invalid input in netmask field

scripts/python/configure_mgmt_switches.py, scripts/python/gen.py, scripts/python/lib/argparse_gen.py, software/file-lists-wmla120.yml, software/file-lists-wmla120_x86_64.yml, software/pkg-lists-wmla120_x86_64.yml, software/wmla120.py, tests/unit/test_pup_software.py
Incrimentally adding changes to wmla120 for x86_64 hardware. Version 1 added arch x86_64 in sofware instance and in command line interface.
=> feat: Add x86_64 arch version 1

scripts/python/engr_mode.py, scripts/python/repos.py, software/pkg-lists-wmla120.yml, software/wmla120.py
Create directory when getting dependencies repo.
Fix __init__ of get_yum_repo_from_repo.
Prompt user to clean caches in eng mode.
=> fix: Repo sync fixes

software/wmla120_ansible/configure_spectrum_conductor.yml
Update configure_spectrum_conductor.yml to install python-lmdb-0.94.
=> fix: Update configure_spectrum_conductor playbook

software/pkg-lists-wmla120.yml, software/wmla120.py
Remove a bug accidently introduced while debugging and left in code.
Update file sanity check for Conda repos.
=> fix: Remove debug related bug

scripts/python/cobbler_add_distros.py
Handle unrecognized OS distro in cobbler_add_distros
=> fix: Handle unrecognized OS distro

scripts/python/repos.py, software/pkg-lists-wmla120_x86_64.yml, software/wmla120.py
This fix adds other missing code implementation from prior merge issue.
=> fix: Merge Changes for x86_64 missing from merge

software/wmla120_ansible/envs_spectrum_conductor_dli_template.yml
Fix is to change comment to add 7.6 version of Rhel instead of 7.5 ...
=> fix: Change comment to state 7.6 version of Rhel

scripts/python/repos.py, software/wmla120.py
Add x86 comment in print statement
=> fix: Fix issue 7691 by adding correct comment

software/pkg-lists-wmla120_x86_64.yml
Remove incorrect package from kernel yum list
=> fix: remove package from x86_64 package list

scripts/python/lib/utilities.py, scripts/python/nginx_setup.py
Handle blank lines in nginx.conf. Start nginx service in case it
is stopped.
=> fix: Enhance nginx setup

scripts/python/lib/utilities.py, software/wmla120.py
For EPEL and RHEL repos, download the most recent version
of packages in addition to the specified versions.
For Cuda drivers only download the specified versions.
=> feat: Optional download latest yum packages

software/file-lists-wmla120.yml, software/pkg-lists-wmla120.yml
Update pkg-list-wmla120.yml to accomodate latest available versions of
all dependent packages on Power.
Update file-list-wmla120.yml to release level packages on Power.
=> chore: Update package and file lists

software/get-dependent-packages.sh
Add architecture argument to get-dependent-packages.sh
and download packages based on the architecture of the
remote node.
=> fix: Update get-dependent-packages.sh

software/wmla120.py
=> fix: Link in wmla120.py --README

software/wmla120.py
Change 'srv' to '/srv' in setup nginx call in wmla120.py
=> fix: Configure nginx for software installer

docs/Appendix-B.rst
Fix command for enabling EPEL repo.
=> docs: Fix error in Appendix B

software/wmla120.py
=> fix: Issue 8157 Address Cuda Driver Repository name

software/wmla120.py
Check that nginx can access a newly created directory under the
software installer 'root' directory.
=> feat: Enhance nginx status check

scripts/python/software_hosts.py
Change help (comments) in software inventory file.
=> fix: Software inventory help

software/wmla120.py
Configure the firewall if it is already running, but do not enable
or start it.
Advise the user to start the firewall if it is not running.
=> fix: Configure firewall if enabled

scripts/python/getdeps2.py
After running through install procedure with engineering mode enabled, pre/post data will transfer to deployer. Phase 2 of dependency tooling then parses through data. With an updated file check, missing files are prompted to differentiate between missing files error and code error problems. The addition of file check for pip and conda pre and post data is also added.
=> fix: addressed changes to getdeps2.py

software/pkg-lists-wmla120.yml, software/pkg-lists-wmla120_x86_64.yml
Add pcsc-lite-libs to dependencies repos
=> chore: Update package lists

scripts/python/lib/utilities.py, software/init_clients.yml, software/wmla120.py, software/wmla120_ansible/disable_udev_mem_auto_onlining.yml, software/wmla120_ansible/run.yml
This change is to change ansible playbooks to only gather facts from network and modify power to get
cpu processor by /proc/cpuinfo.
=> fix: Change gather facts to gather only network

software/get-dependent-packages.sh
Enhance get-dependent-packages.sh to download latest version of
packages along with the mentioned version.
=> fix: Issue 8592 Enhance get-dependent-packages.sh to download latest version

tox.ini
=> test: Updates to tox.ini to exclude pup-venv environment and address bash location change

software/wmla120_ansible/engr_mode_client_conda_update_cache.yml
Add -y argument to conda clean all command.
modified:   software/wmla120_ansible/engr_mode_client_conda_update_cache.yml
=> fix: Conda clean cache

scripts/python/set_bootdev_clients.py, scripts/python/set_power_clients.py, scripts/python/validate_cluster_hardware.py
Change some BMC 'errors' to info.
=> fix: Enhance feedback during deploy

scripts/create-base-dir-wmla120, scripts/python/create_base_dir_wmla120.py, scripts/python/gen.py, scripts/python/lib/argparse_gen.py, scripts/python/lib/genesis.py, scripts/python/nginx_setup.py, scripts/python/osinstall.py, scripts/python/repos.py, software/content-wmla120.yml, software/wmla120.py, software/wmla120_ansible/anaconda_prep.yml, software/wmla120_ansible/configure_spectrum_conductor.yml, software/wmla120_ansible/entitle_spectrum_conductor_dli.yml, software/wmla120_ansible/entitle_spectrum_conductor_with_spark.yml, software/wmla120_ansible/install_spectrum_conductor_dli.yml, software/wmla120_ansible/install_spectrum_conductor_with_spark.yml, software/wmla120_ansible/wmla_license_check_and_install_to_root.yml, software/wmla120_ansible/wmla_license_install.yml
Generate the software-vars content needed for install at install
time.
Add new 'content' file which is to be used by all code needing to
load or refer to the content yaml in the PowerUp software server.
=> refactor: Generate software-vars

software/wmla120_ansible/create_nfs_server.yml, software/wmla120_ansible/file.yml, software/wmla120_ansible/filesystem.yml, software/wmla120_ansible/mount.yml, software/wmla120_ansible/network_interface.yml, software/wmla120_ansible/nfs_server.yml, software/wmla120_ansible/parted.yml, software/wmla120_ansible/resolve_server_hostnames.yml, software/wmla120_ansible/route.yml, software/wmla120_ansible/service.yml, software/wmla120_ansible/templates/create_exports.j2, software/wmla120_ansible/templates/make_interfaces_rhel.j2, software/wmla120_ansible/templates/make_routes_rhel.j2, software/wmla120_ansible/yum.yml, software/wmla120_ansible/yum_repository.yml
Building blocks to create ansible playbooks to setup public and private networks. This is the logic running the descriptive commands in a later commit.
=> feat: First layer of iterative ansible playbooks

software/wmla120_ansible/env_vars/setup_ftp3_env_vars.yml, software/wmla120_ansible/env_vars/setup_public_env_vars.yml, software/wmla120_ansible/public_net.yml, software/wmla120_ansible/subscribe_ftp3.yml
This feature adds public network access and repo setup.Also adds ansible way of creating subscription with redhat ftp3 satellite.
=> feat: Setup public access to clients

software/wmla120_ansible/env_vars/setup_private_env_vars.yml, software/wmla120_ansible/private_net.yml
The air gapped installation requires networks to have no public access and this feature adds that capability.
=> feat: This feature sets up clients for air gapped install

software/wmla120_ansible/uninstall_wmla120.yml
This feature adds uninstall of wmla120 software from all clients.
=> feat: Uninstall wmla120

scripts/python/gen.py, scripts/python/lib/argparse_gen.py, software/wmla120.py
This feature adds ability to run ansible tasks from pup software command line by just specifying:
`pup software wmla120.py --install --run_ansible_task sudo_test.yml`. This will look in software directory of wmla120 release.
=> feat: Run ansible task from pup software command line

docs/Appendix-B.rst, docs/Running-paie.rst
WMLA installer currently only supports the licensed version of WMLA
on Power hardware.
=> docs: Update support statements

software/wmla120.py
Write software-vars.yml file after running _update_software_vars.
Previously was only being saved after prep stage.
=> fix: Write software-vars file

scripts/install.sh
Create ansible.log at install time.
=> fix: Insure ansible.log is owned by user

scripts/python/getdeps2.py
=> fix: Get noarch conda items

scripts/python/repos.py, software/wmla120.py
Insure that SELinux http access is maintained on copy of files
into the software server.
=> fix: Replace shutil copy2 with copy in repos.py

software/wmla120.py
Nvidia reverted the libglvnd drivers to an earlier level.
=> fix: Allow alternate versions of cuda drivers

docs/Appendix-A.rst, scripts/pup, scripts/python/archive/__init__.py, scripts/python/archive/bundle.py, scripts/python/gen.py, scripts/python/lib/argparse_gen.py, tests/unit/test_archive.py
In support of archiving directories this patch adds:
tar / zip the Power-up software installer repos
tar / zip the Power-up software
Install Power-up from tar/zip
recreate repos on Power-up server
Also, the bundle.py script is able to be ran standalone
only with python 2.7 installed.
=> feat: Archive /srv and power up software

software/wmla120.py
=> fix: Corrected typo in pre-install validation status

os-images/config/RHEL-7-default.ks.j2
Remove additional fields from output of ip route get.
=> fix: Kickstart jinja2 template

software/pkg-lists-wmla120.yml, software/wmla120.py
Use package list from pkg-list-wmlannn.yml
=> fix: Properly check for conda packages

scripts/python/gen.py, scripts/python/getdeps2.py, software/wmla120.py, software/wmla120_ansible/engr_mode_client_pre_install_gather.yml, software/wmla120_ansible/nfs_server.yml, software/wmla120_ansible/powerai_tuning.yml, software/wmla120_install_procedure.yml, software/yamlvault.py
This feature adds getdeps2.py parsing and creation
of pkg-lists file. This will create a pkg list file
for specific release if told otherwise will create it
on dependencies repo. Minor fixes added to other components.
=> feat: Add Parsing of yml files for pkg list file

software/wmla120_ansible/validate_firewall_setup.yml
Addresses the state of firewall is active but disabled
=> fix: Updates to validate firewall setup

scripts/python/osinstall.py
Update status portion of profile.yml when updating a previous
profile.yml version.
=> fix: Update profile.yml

scripts/python/repos.py, software/wmla120_ansible/validate_shared_storage_config.yml, tox.ini
This PR addresses all remaining tox errors. Subsequent PRs will be required to pass tox before being merged into master branch.
=> Tox runs without errors

scripts/python/software_hosts.py
The logic to add client node host keys assumed that the user would not
be running as 'root'.
=> fix: Add 'root' user case for host key collection

scripts/python/lib/utilities.py
Utility functions used for user input should have comprehensive debug
logging enabled.
=> feat: Add additional debug logging to user inputs

software/wmla121.py
self.eval_ver is used to identify the wmla121 eval setup
=> fix: Select WMLA eval content

scripts/python/repos.py
There is no need to build repo indexes manually when Nginx auto index is
enabled. In some cases packages have been omitted from the index causing
false warnings of incomplete-ness.
=> fix: Do not manually build repo indexes
